name = "manga-api-4"
main = "./dist/worker.js"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

account_id = "9befea142865276dab131815c729cd8f"

[[d1_databases]]
binding = "DB"
database_name = "manga-db"
database_id = "d2c207fd-4ff4-41ce-b954-760ac33da037"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "725eea4df1ee413ead6324f23e7b18f8"

[browser]
binding = "MY_BROWSER"
remote = true

[vars]
EVICTION_OWNER = "0"
PEER_URLS = "https://manga-api.oktz.workers.dev,https://manga-api-2.tzok5555.workers.dev,https://manga-api-3.dwikaoktyffan.workers.dev,https://manga-api-4.oktznih.workers.dev"
PEER_INDEX = "3"
AUTH_PUBLIC_KEYS = '[{"kid":"manga-api","key":{"key_ops":["verify"],"ext":true,"kty":"EC","x":"7t_Lay1YVxbVCkR7nNNMsNOTzOuy7B2GJNnGIaXgft4","y":"GmlK-twGCtCS2wXkZwllV2vO1ACUTPph75Pkh11yCTs","crv":"P-256"}},{"kid":"manga-api-2","key":{"key_ops":["verify"],"ext":true,"kty":"EC","x":"TY2VCzF0ShaaZ7CWFmr8QQ1-4Y1kVBM_Bq68kIbh_1U","y":"fIe-sM7w-tAOeGKhT40D5-1lSkon4b0aYT0Qn96ZBN0","crv":"P-256"}},{"kid":"manga-api-3","key":{"key_ops":["verify"],"ext":true,"kty":"EC","x":"0fJmUlRFoNlFu-TdYLhxA-US4-vYjSViLqCNaKg3ymY","y":"X5M9xNq0NjrwY0Udpg9MqgMI76XEaRCg_arDRWLh0rY","crv":"P-256"}},{"kid":"manga-api-4","key":{"key_ops":["verify"],"ext":true,"kty":"EC","x":"rUDSZFmCL79QnJUnJsAmEu5RjuU8u0nh0CV6_FZXn0c","y":"rJdiYevESLD2cdGe_ncmrzu6PppMl3UbERk88t4I56U","crv":"P-256"}}]'

[cache]
enabled = true

[triggers]
crons = ["0 * * * *"]
